require("UI/StartPanel")
require("UI/LoginPanel")
require("UI/RegisterPanel")
require("UI/MainPanel")
PreMatch1V1Panel = require("UI/PreMatch1V1Panel")
GameMatch1V1Panel =require("UI/GameMatch1V1Panel")
PreMatch1V3Panel = require("UI/PreMatch1V3Panel")
GameMatch1V3Panel =require("UI/GameMatch1V3Panel")
require("UI/TipsPanel")
require("UI/PlayEndPanel")